Repository shim-pyoo/ShimPyo-Server, pull requests merged in 2024-09, with the labels that each got.

#54 ✨ FEAT. 이번주 쉼 상태 조회
  src/main/java/com/hsu/shimpyoo/domain/breathing/repository/DailyPefRepository.java
  src/main/java/com/hsu/shimpyoo/domain/breathing/service/BreathingService.java
  src/main/java/com/hsu/shimpyoo/domain/breathing/web/controller/BreathingController.java
Labels: ✨feat, :hatching_chick: jungeun

#57 ✨ FEAT. 월간 평균 최대호기량 조회
  src/main/java/com/hsu/shimpyoo/domain/breathing/service/BreathingService.java
  src/main/java/com/hsu/shimpyoo/domain/breathing/web/controller/BreathingController.java
Labels: ✨feat, :hatching_chick: jungeun

#58 :sparkles: FEAT. 재측정 + 오늘의 결과 조회
  src/main/java/com/hsu/shimpyoo/domain/breathing/entity/Breathing.java
  src/main/java/com/hsu/shimpyoo/domain/breathing/repository/BreathingRepository.java
  src/main/java/com/hsu/shimpyoo/domain/breathing/repository/DailyPefRepository.java
  src/main/java/com/hsu/shimpyoo/domain/breathing/service/BreathingCheckService.java
  src/main/java/com/hsu/shimpyoo/domain/breathing/service/BreathingCheckServiceImpl.java
  src/main/java/com/hsu/shimpyoo/domain/breathing/service/BreathingService.java
  src/main/java/com/hsu/shimpyoo/domain/breathing/web/controller/BreathingCheckController.java
  src/main/java/com/hsu/shimpyoo/domain/breathing/web/controller/BreathingController.java
  src/main/java/com/hsu/shimpyoo/global/exception/CustomExceptionHandler.java
  src/main/java/com/hsu/shimpyoo/global/exception/GlobalExceptionHandler.java
Labels: ✨feat, :rabbit: hyejeong

#60 ✨ FEAT. 병원 방문 일정 조회
  src/main/java/com/hsu/shimpyoo/domain/hospital/repository/HospitalVisitRepository.java
  src/main/java/com/hsu/shimpyoo/domain/hospital/service/HospitalService.java
  src/main/java/com/hsu/shimpyoo/domain/hospital/service/HospitalServiceImpl.java
  src/main/java/com/hsu/shimpyoo/domain/hospital/web/controller/HospitalController.java
  src/main/java/com/hsu/shimpyoo/domain/hospital/web/dto/HospitalVisitDto.java
Labels: ✨feat, :rabbit: hyejeong

#61 ✨ FEAT. 지난달 이번달 비교
  src/main/java/com/hsu/shimpyoo/domain/breathing/service/BreathingService.java
  src/main/java/com/hsu/shimpyoo/domain/breathing/web/controller/BreathingController.java
Labels: ✨feat, :hatching_chick: jungeun

#63 ✨ FEAT. 병원 방문까지 남은 시간 조회 기능 구현
  src/main/java/com/hsu/shimpyoo/domain/hospital/repository/HospitalVisitRepository.java
  src/main/java/com/hsu/shimpyoo/domain/hospital/service/HospitalService.java
  src/main/java/com/hsu/shimpyoo/domain/hospital/service/HospitalServiceImpl.java
  src/main/java/com/hsu/shimpyoo/domain/hospital/web/controller/HospitalController.java
  src/main/java/com/hsu/shimpyoo/domain/hospital/web/dto/HospitalVisitTimeLeftDto.java
Labels: ✨feat, :rabbit: hyejeong

#68 ✨ FEAT. 약 복용 시간 조회
  src/main/java/com/hsu/shimpyoo/domain/medicine/service/MedicineService.java
  src/main/java/com/hsu/shimpyoo/domain/medicine/web/controller/MedicineController.java
  src/main/java/com/hsu/shimpyoo/domain/medicine/web/dto/MedicineTimeSettingDto.java
Labels: ✨feat, :hatching_chick: jungeun

#71 🐛 FIX. Flask 서버와의 통신 수정
  src/main/java/com/hsu/shimpyoo/domain/breathing/service/BreathingCheckServiceImpl.java
  src/main/java/com/hsu/shimpyoo/domain/breathing/service/BreathingService.java
Labels: :recycle: enhancement, 🚨fix, :rabbit: hyejeong

#77 ✨ FEAT. AI 채팅 기능 구현
  build.gradle
  src/main/java/com/hsu/shimpyoo/domain/chatbot/entity/Chat.java
  src/main/java/com/hsu/shimpyoo/domain/chatbot/entity/ChatRoom.java
  src/main/java/com/hsu/shimpyoo/domain/chatbot/repository/ChatRepository.java
  src/main/java/com/hsu/shimpyoo/domain/chatbot/repository/ChatRoomRepository.java
  src/main/java/com/hsu/shimpyoo/domain/chatbot/service/ChatRoomService.java
  src/main/java/com/hsu/shimpyoo/domain/chatbot/service/ChatRoomServiceImpl.java
  src/main/java/com/hsu/shimpyoo/domain/chatbot/service/ChatService.java
  src/main/java/com/hsu/shimpyoo/domain/chatbot/service/ChatServiceImpl.java
  src/main/java/com/hsu/shimpyoo/domain/chatbot/web/controller/ChatController.java
  src/main/java/com/hsu/shimpyoo/domain/chatbot/web/dto/ChatListDto.java
  src/main/java/com/hsu/shimpyoo/domain/chatbot/web/dto/ChatMessageDto.java
  src/main/java/com/hsu/shimpyoo/domain/chatbot/web/dto/ChatQuestionDto.java
  src/main/java/com/hsu/shimpyoo/domain/chatbot/web/dto/ChatRequestDto.java
  src/main/java/com/hsu/shimpyoo/domain/chatbot/web/dto/ChatResponseDto.java
  src/main/java/com/hsu/shimpyoo/domain/chatbot/web/dto/ChatRoomListDto.java
  src/main/java/com/hsu/shimpyoo/domain/chatbot/web/dto/ModifyChatRoomTitleDto.java
  src/main/java/com/hsu/shimpyoo/global/enums/TFStatus.java
  src/main/java/com/hsu/shimpyoo/global/gpt/OpenAiConfig.java
Labels: :recycle: enhancement, ✨feat, :rabbit: hyejeong

#80 🐛 FIX. 호흡 측정 및 조회 시, db에 4~5번씩 들어가는 오류 수정
  src/main/java/com/hsu/shimpyoo/domain/breathing/service/BreathingCheckServiceImpl.java
  src/main/java/com/hsu/shimpyoo/domain/breathing/service/BreathingService.java
  src/main/java/com/hsu/shimpyoo/domain/breathing/web/controller/BreathingController.java
Labels: 🚨fix, :rabbit: hyejeong

#83 :heavy_plus_sign: ADD. 채팅방 생성 시, 생성된 채팅방의 기본키를 반환하도록 추가
  src/main/java/com/hsu/shimpyoo/domain/chatbot/service/ChatRoomServiceImpl.java
Labels: :recycle: enhancement, :rabbit: hyejeong

#85 ♻️ REFACTOR. 파이썬 코드 디벨롭에 따른 통신 코드 리팩토링
  400-1.m4a
  420.m4a
  89.m4a
  src/main/java/com/hsu/shimpyoo/domain/breathing/service/BreathingCheckService.java
  src/main/java/com/hsu/shimpyoo/domain/breathing/service/BreathingCheckServiceImpl.java
  src/main/java/com/hsu/shimpyoo/domain/breathing/web/controller/BreathingCheckController.java
Labels: :recycle: enhancement, :rabbit: hyejeong
