Repository shim-pyoo/ShimPyo-Server, pull requests merged in 2024-08, with the labels that each got.

#3 ✨ FEAT. JWT 로그인 및 회원가입 구현
  build.gradle
  src/main/java/com/hsu/shimpyoo/global/controller/CustomErrorController.java
  src/main/java/com/hsu/shimpyoo/global/entity/User.java
  src/main/java/com/hsu/shimpyoo/global/jwt/security/JwtTokenFilter.java
  src/main/java/com/hsu/shimpyoo/global/jwt/security/JwtTokenProvider.java
  src/main/java/com/hsu/shimpyoo/global/jwt/security/MyUserDetails.java
  src/main/java/com/hsu/shimpyoo/global/jwt/security/SecurityConfig.java
  src/main/java/com/hsu/shimpyoo/global/jwt/util/AuthenticationUserUtils.java
  src/main/java/com/hsu/shimpyoo/global/response/CustomAPIResponse.java
  src/main/java/com/hsu/shimpyoo/global/user/controller/UserController.java
  src/main/java/com/hsu/shimpyoo/global/user/dto/SignInReqDto.java
  src/main/java/com/hsu/shimpyoo/global/user/dto/SignInResDto.java
  src/main/java/com/hsu/shimpyoo/global/user/dto/SignUpDto.java
  src/main/java/com/hsu/shimpyoo/global/user/repository/UserRepository.java
  src/main/java/com/hsu/shimpyoo/global/user/service/UserService.java
Labels: ✨feat, :hatching_chick: jungeun

#11 :bug: FIX. 병원 검색 기능을 키워드 기반으로 수정
  src/main/java/com/hsu/shimpyoo/ShimpyooApplication.java
  src/main/java/com/hsu/shimpyoo/domain/hospital/entity/Hospital.java
  src/main/java/com/hsu/shimpyoo/domain/hospital/repository/HospitalRepository.java
  src/main/java/com/hsu/shimpyoo/domain/hospital/service/HospitalService.java
  src/main/java/com/hsu/shimpyoo/domain/hospital/service/HospitalServiceImpl.java
  src/main/java/com/hsu/shimpyoo/domain/hospital/web/dto/HospitalRequestDto.java
  src/main/java/com/hsu/shimpyoo/domain/hospital/web/dto/HospitalResponseDto.java
  src/main/java/com/hsu/shimpyoo/domain/user/dto/SignInReqDto.java
  src/main/java/com/hsu/shimpyoo/domain/user/dto/SignUpDto.java
  src/main/java/com/hsu/shimpyoo/domain/user/entity/User.java
  src/main/java/com/hsu/shimpyoo/domain/user/repository/UserRepository.java
  src/main/java/com/hsu/shimpyoo/domain/user/service/UserService.java
  src/main/java/com/hsu/shimpyoo/global/config/DataInitializer.java
  src/main/java/com/hsu/shimpyoo/global/security/service/MyUserDetails.java
Labels: 🚨fix, :rabbit: hyejeong

#13 🐛 FIX. 회원가입시 입력받을 정보 추가
  src/main/java/com/hsu/shimpyoo/domain/user/dto/SignUpDto.java
  src/main/java/com/hsu/shimpyoo/domain/user/entity/User.java
Labels: 🚨fix, :hatching_chick: jungeun

#16 :bug: FIX. 더 많은 병원 정보를 불러올 수 있도록 수정
  src/main/java/com/hsu/shimpyoo/domain/hospital/service/HospitalServiceImpl.java
  src/main/java/com/hsu/shimpyoo/domain/hospital/web/controller/HospitalController.java
  src/main/java/com/hsu/shimpyoo/global/config/DataInitializer.java
Labels: 🚨fix, :rabbit: hyejeong

#17 ✨ FEAT. 회원가입 시 입력받은 pef 값을 breathingRate로 설정
  src/main/java/com/hsu/shimpyoo/domain/breathing/entity/Breathing.java
  src/main/java/com/hsu/shimpyoo/domain/breathing/repository/BreathingRepository.java
  src/main/java/com/hsu/shimpyoo/domain/user/entity/User.java
  src/main/java/com/hsu/shimpyoo/domain/user/service/UserService.java
Labels: ✨feat, :hatching_chick: jungeun

#18 ✨ FEAT. 병원 방문일 설정 기능
  src/main/java/com/hsu/shimpyoo/domain/hospital/entity/Hospital.java
  src/main/java/com/hsu/shimpyoo/domain/hospital/entity/HospitalVisit.java
  src/main/java/com/hsu/shimpyoo/domain/hospital/repository/HospitalVisitRepository.java
  src/main/java/com/hsu/shimpyoo/domain/hospital/service/HospitalService.java
  src/main/java/com/hsu/shimpyoo/domain/hospital/service/HospitalServiceImpl.java
  src/main/java/com/hsu/shimpyoo/domain/hospital/web/controller/HospitalController.java
  src/main/java/com/hsu/shimpyoo/domain/hospital/web/dto/HospitalResponseDto.java
  src/main/java/com/hsu/shimpyoo/domain/hospital/web/dto/HospitalVisitRequestDto.java
  src/main/java/com/hsu/shimpyoo/global/config/DataInitializer.java
  src/main/java/com/hsu/shimpyoo/global/security/config/SecurityConfig.java
  src/main/java/com/hsu/shimpyoo/global/security/jwt/JwtTokenProvider.java
  src/main/java/com/hsu/shimpyoo/global/security/service/MyUserDetails.java
Labels: ✨feat, :rabbit: hyejeong

#21 ♻️ Refactor. 병원 관련 응답 및 요청 개선
  src/main/java/com/hsu/shimpyoo/domain/hospital/entity/Hospital.java
  src/main/java/com/hsu/shimpyoo/domain/hospital/service/HospitalService.java
  src/main/java/com/hsu/shimpyoo/domain/hospital/service/HospitalServiceImpl.java
  src/main/java/com/hsu/shimpyoo/domain/hospital/web/controller/HospitalController.java
  src/main/java/com/hsu/shimpyoo/domain/hospital/web/dto/HospitalResponseDto.java
  src/main/java/com/hsu/shimpyoo/domain/hospital/web/dto/HospitalSearchRequestDto.java
  src/main/java/com/hsu/shimpyoo/domain/hospital/web/dto/HospitalSearchResponseDto.java
  src/main/java/com/hsu/shimpyoo/domain/hospital/web/dto/HospitalVisitRequestDto.java
  src/main/java/com/hsu/shimpyoo/domain/hospital/web/dto/HospitalVisitSetRequestDto.java
  src/main/java/com/hsu/shimpyoo/global/config/DataInitializer.java
Labels: :recycle: enhancement, :rabbit: hyejeong

#24 ✨ FEAT. 약 복용까지 남은 시간 조회
  src/main/java/com/hsu/shimpyoo/domain/medicine/controller/MedicineController.java
  src/main/java/com/hsu/shimpyoo/domain/medicine/repository/MedicineRepository.java
  src/main/java/com/hsu/shimpyoo/domain/medicine/service/MedicineService.java
  src/main/java/com/hsu/shimpyoo/domain/medicine/service/MedicineServiceImpl.java
Labels: ✨feat, :hatching_chick: jungeun

#25 👷 CI. 파이프라인 구축
  Dockerfile
Labels: :rabbit: hyejeong, 👷 CI

#29 ✨ FEAT. 오늘의 쉼 결과 조회 기능
  src/main/java/com/hsu/shimpyoo/domain/breathing/controller/BreathingController.java
  src/main/java/com/hsu/shimpyoo/domain/breathing/dto/BreathingRequestDto.java
  src/main/java/com/hsu/shimpyoo/domain/breathing/entity/Breathing.java
  src/main/java/com/hsu/shimpyoo/domain/breathing/repository/BreathingRepository.java
  src/main/java/com/hsu/shimpyoo/domain/breathing/service/BreathingService.java
Labels: ✨feat, :hatching_chick: jungeun

#30 ✨ FEAT. 오늘의 쉼 지난 7일간 측정 내역
  src/main/java/com/hsu/shimpyoo/domain/breathing/controller/BreathingController.java
  src/main/java/com/hsu/shimpyoo/domain/breathing/repository/BreathingRepository.java
  src/main/java/com/hsu/shimpyoo/domain/breathing/service/BreathingService.java
Labels: ✨feat, :hatching_chick: jungeun

#31 ✨ FEAT. 호흡 녹음 파일 S3에 업로드
  build.gradle
  src/main/java/com/hsu/shimpyoo/domain/breathing/controller/BreathingController.java
  src/main/java/com/hsu/shimpyoo/domain/breathing/dto/BreathingUploadRequestDto.java
  src/main/java/com/hsu/shimpyoo/domain/breathing/entity/BreathingFile.java
  src/main/java/com/hsu/shimpyoo/domain/breathing/repository/BreathingFileRepository.java
  src/main/java/com/hsu/shimpyoo/domain/breathing/service/BreathingService.java
  src/main/java/com/hsu/shimpyoo/domain/hospital/service/HospitalServiceImpl.java
  src/main/java/com/hsu/shimpyoo/global/aws/s3/config/S3Config.java
  src/main/java/com/hsu/shimpyoo/global/aws/s3/service/S3Service.java
Labels: ✨feat, :rabbit: hyejeong

#35 ✨ 나의 기준 최대호기량 조회 기능 구현
  src/main/java/com/hsu/shimpyoo/domain/breathing/controller/BreathingController.java
  src/main/java/com/hsu/shimpyoo/domain/breathing/service/BreathingService.java
Labels: ✨feat, :hatching_chick: jungeun

#42 ✨ FEAT. 플라스크 서버와 통신하여 PEF 추출하기
  src/main/java/com/hsu/shimpyoo/ShimpyooApplication.java
  src/main/java/com/hsu/shimpyoo/domain/breathing/entity/Breathing.java
  src/main/java/com/hsu/shimpyoo/domain/breathing/entity/DailyPef.java
  src/main/java/com/hsu/shimpyoo/domain/breathing/repository/BreathingFileRepository.java
  src/main/java/com/hsu/shimpyoo/domain/breathing/repository/BreathingRepository.java
  src/main/java/com/hsu/shimpyoo/domain/breathing/service/BreathingCheckService.java
  src/main/java/com/hsu/shimpyoo/domain/breathing/service/BreathingCheckServiceImpl.java
  src/main/java/com/hsu/shimpyoo/domain/breathing/service/BreathingService.java
  src/main/java/com/hsu/shimpyoo/domain/breathing/web/controller/BreathingCheckController.java
  src/main/java/com/hsu/shimpyoo/domain/breathing/web/controller/BreathingController.java
  src/main/java/com/hsu/shimpyoo/domain/breathing/web/dto/BreathingFlaskRequestDto.java
  src/main/java/com/hsu/shimpyoo/domain/breathing/web/dto/BreathingPefDto.java
  src/main/java/com/hsu/shimpyoo/domain/breathing/web/dto/BreathingUploadRequestDto.java
  src/main/java/com/hsu/shimpyoo/domain/user/service/UserService.java
Labels: :recycle: enhancement, ✨feat, :rabbit: hyejeong

#45 ✨ FEAT. 주간 평균 최대호기량 비교
  src/main/java/com/hsu/shimpyoo/domain/breathing/service/BreathingService.java
  src/main/java/com/hsu/shimpyoo/domain/breathing/web/controller/BreathingController.java
Labels: ✨feat, :hatching_chick: jungeun

#49 🎨 ADD. 주간 평균 최대호기량 비교 코드 추가
  src/main/java/com/hsu/shimpyoo/domain/breathing/web/controller/BreathingController.java
Labels: ✨feat, :hatching_chick: jungeun

#50 ♻️ Refactor. 호흡 수치 계산 로직 수정 및 응답 개선
  src/main/java/com/hsu/shimpyoo/domain/breathing/repository/BreathingRepository.java
  src/main/java/com/hsu/shimpyoo/domain/breathing/service/BreathingCheckService.java
  src/main/java/com/hsu/shimpyoo/domain/breathing/service/BreathingCheckServiceImpl.java
  src/main/java/com/hsu/shimpyoo/domain/breathing/service/BreathingService.java
  src/main/java/com/hsu/shimpyoo/domain/breathing/web/controller/BreathingCheckController.java
  src/main/java/com/hsu/shimpyoo/domain/breathing/web/controller/BreathingController.java
  src/main/java/com/hsu/shimpyoo/domain/breathing/web/dto/BreathingRequestDto.java
  src/main/java/com/hsu/shimpyoo/domain/hospital/service/HospitalServiceImpl.java
  src/main/java/com/hsu/shimpyoo/domain/user/entity/User.java
  src/main/java/com/hsu/shimpyoo/domain/user/service/UserService.java
  src/main/java/com/hsu/shimpyoo/global/exception/GlobalExceptionHandler.java
Labels: :recycle: enhancement, 🚨fix, :rabbit: hyejeong
